<?php

declare(strict_types=1);

namespace pixelwhiz\animalcoins;

use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\Config;

class AnimalCoins extends PluginBase {

    public static $instance;
    public Config $config;

    public function onEnable(): void
    {
        self::$instance = $this;
        $this->getServer()->getPluginManager()->registerEvents(new EventListener($this), $this);
        parent::onEnable(); // TODO: Change the autogenerated stub
        $this->saveDefaultConfig();
        $this->saveResource("config.yml");
        $this->config = new Config($this->getDataFolder() . "config.yml");
        $this->getServer()->getLogger()->info("Plugin Enabled by DpGenx!");
    }

    public function onDisable(): void
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
        $this->getServer()->getLogger()->info("Plugin Disabled by DpGenx!");
    }

    public static function getInstance(): AnimalCoins {
        return self::$instance;
    }

}
